# Generated by Django 3.0.7 on 2020-06-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigerpath', '0017_major_supported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='term_code',
            field=models.CharField(db_index=True, default=1202, max_length=4, unique=True),
        ),
    ]
